version: '3.7'
services:
    web:
        build: ./app
        restart: always
        ports:
          - "443:443"
          - "8080:8080"
          - "3000:3000"
        depends_on:
          - db
        volumes:
            - ./app:/src
        environment:
            NODE_ENV: development
            PORT: 3000
    db:
         image: mongo
         restart: always
         environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: changethistoamoresecurepassword
         volumes:
           - ./data:/data/db
